language: python

env:
  - TWISTED=Twisted==15.0 RUNTESTS=trial
  - TWISTED=Twisted==15.1 RUNTESTS=trial

python:
  - 2.6
  - 2.7
  - pypy

matrix:
  include:
    - python: 3.4
      env: TWISTED=Twisted==16.1 RUNTESTS="python -m unittest discover"
    - python: 3.5
      env: TWISTED=Twisted==16.1 RUNTESTS="python -m unittest discover"

install:
  - python setup.py --version
  - pip install -q $TWISTED pyflakes
  - python setup.py -q install

script:
  - $RUNTESTS crochet.tests
  - pyflakes crochet

notifications:
  email: false
