env:
    - TWISTED=Twisted==12.0
    - TWISTED=Twisted==12.1
    - TWISTED=Twisted==12.2
    - TWISTED=Twisted==12.3
    - TWISTED=Twisted==13.0
    - TWISTED=Twisted==13.1
    - TWISTED=Twisted==13.2

matrix:
    include:
        python:
            - 3.3
        env:
            - TWISTED=git+https://github.com/twisted/twisted.git

language: python

python:
    - 2.6
    - 2.7
    - pypy

install:
    - python setup.py --version
    - pip install -q --no-use-wheel $TWISTED --use-mirrors
    - python setup.py -q install

script: trial crochet

notifications:
  email: false
