env:
    - TWISTED=Twisted==11.0
    - TWISTED=Twisted==11.1
    - TWISTED=Twisted==12.0
    - TWISTED=Twisted==12.1
    - TWISTED=Twisted==12.2
    - TWISTED=Twisted==12.3
    - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk

language: python

python:
    - 2.6
    - 2.7
    - pypy
# In theory Python 3.3 should work, but that requires Twisted to be more
# easily installable on 3.3...
#    - 3.3

install:
    - pip install -q $TWISTED --use-mirrors
    - python setup.py -q install

script: trial crochet

notifications:
  email: false
