language: python

env:
  - TWISTED=Twisted==15.0 RUNTESTS=trial
  - TWISTED=Twisted RUNTESTS=trial

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6-dev
  - pypy

install:
  - python setup.py --version
  - pip install -q $TWISTED pyflakes
  - python setup.py -q install

script:
  - $RUNTESTS crochet.tests
  - pyflakes crochet

notifications:
  email: false
