language: python

env:
  # Oldest supported version:
  - TWISTED=Twisted==16.0
  # Latest Twisted:
  - TWISTED=Twisted

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

install:
  - python setup.py --version
  - pip install -q $TWISTED flake8 pylint
  - python setup.py -q install

script:
  - trial crochet.tests
  - flake8 crochet
  - pylint crochet

notifications:
  email: false
